# Generated by Django 5.1.7 on 2025-03-20 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0001_initial'),
        ('hawwa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminops.department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(
                to='adminops.Department',
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True
            ),
        ),
    ]
