# Generated by Django 5.1.6 on 2025-02-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_types', models.JSONField()),
                ('availability', models.BooleanField(default=True)),
                ('amenities_inclusive', models.TextField()),
                ('amenities_exclusive', models.TextField()),
            ],
        ),
    ]
