# Generated by Django 5.1.6 on 2025-03-04 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities_exclusive',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='amenities_inclusive',
        ),
    ]
